name = "polling-app"
main = "src/index.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "POLL", class_name = "Poll" }
]

[[migrations]]
tag = "v1"
new_classes = ["Poll"]

# Thay ID này bằng ID thực từ output của wrangler kv namespace create
[[kv_namespaces]]
binding = "POLLS_KV"
id = "646885645fe84edc83137e1f25584f9e"
preview_id = "dbbad7a443af44fba6832b67002e48c2"

[env.production]
name = "polling-app"

[env.preview]
name = "polling-app-preview"